### ISSUE TITLE
Add rule for `forEach`

### ISSUE THREAD

**Issue by jsit** [Volox/eslint-plugin-ie11#2]
`forEach` not supported in IE11:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Browser_compatibility

**Comment by Volox** [comment]
I just double checked the link and it seems to be supported in IE11, you can also see [kangax link](http://kangax.github.io/compat-table/es5/#test-Array_methods_Array.prototype.forEach_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;)

`forEach` is not supported on NodeList see Can I use: [link](https://caniuse.com/#search=foreach)
